# Specify version format
version: "{build}"

os:
#  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\Dusk

before_build:
  - cmd: set DUSK_INSTALL_DIR=C:\projects\Dusk
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" if "%PLATFORM%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 15 2017
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" if "%PLATFORM%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 15 2017 Win64

build_script:
  - cmd: cd C:\projects\Dusk
  - cmd: mkdir Build
  - cmd: cd Build
  - cmd: cmake -DBUILD_TESTS=ON -DBUILD_DEMOS=ON -G "%CMAKE_GENERATOR_NAME%" ..
  - cmd: cmake --build .
  - cmd: cmake --build . --target test

test: off

notifications:
  - provider: Slack
    auth_token:
      secure: ToSdHCPP0Q+7SpqlOWhjSv5YBAL9xPVmJus22nvsbMATMHLDe+VsKj7mYnJaRFYz66ZJq2FEci1CcrcCQOzNgx7Pxcbpsuo0Zg66ZgUJ7DA=
    channel: '#builds'
